<?php
include 'session.php';

?>

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SCU Alumni Events</title>

    <!-- Bootstrap core CSS -->
    <link href="../vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="../style.css" rel="stylesheet">
    <script src="../js/login.js"></script>
    <script src="../js/api.js"></script>
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark static-top" style="background-color: #99303E;">
        <div class="container">
            <a class="navbar-brand" href="admindash.php">SCU Alumni Events</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="adminapprove.php">Approve Events
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="admincreate.php">Create an Event</a>
            </li>
            <li class="nav-item">
               <a class="nav-link" id="logout" onclick="attemptlogout()" href="#">Logout <strong>ADMIN</strong></a>
            </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Event Table -->
    <div class="container" style="margin-top:5%;">
    <h2>Event Calendar</h2>
    <table class="table table-striped" style="margin-top:5%;" id="eventtable">
        <thead>
            <tr>
                <th scope="col">Date</th>
                <th scope="col">Time</th>
                <th scope="col">Event Name</th>
                <th scope="col">Event Description</th>
                <th scope="col">Location</th>
                <th scope="col">Posted by</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody id="tbody">
        </tbody>
    </table>
    </div>

    <!-- Footer -->
    <footer class="footer">
        <div class="container">
            <p></p>
            <span>The content of these web pages is not generated by and does not represent the views of Santa Clara University or any of its departments or organizations.</span>
            <p></p>
        </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="../vendor/jquery/jquery.min.js"></script>
    <script src="../vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <script src="../js/admindash.js"></script>
  </body>

</html>
